development-ping/UNION-frontend

src/common/Map.tsx
src/common/OutMeeti.tsx
src/common/Slide.tsx
src/components/ChatDetail/Content.tsx
src/components/ChatDetail/Footer.tsx
src/components/ChatDetail/Header.tsx
src/components/ChatList/Header.tsx
src/components/ChatList/List.tsx
src/components/ChatList/Lists.tsx
src/components/MeetDetail/Content.tsx
src/components/MeetDetail/Footer.tsx
src/components/Profile/Footer.tsx
src/pages/Board.tsx
src/pages/Board/type.tsx
src/pages/BoardDetail.tsx
src/pages/ChatDetail.tsx
src/pages/ChatList.tsx
src/pages/Home.tsx
src/pages/Meet.tsx
src/pages/MeetDetail.tsx
src/pages/Mypage.tsx

휴대폰으로 봤을때 padding값이 넓어보여서 더 좁게 수정했습니다!
그리고 모임 상세보기에서 작은 화면에서 가로 스크롤이 생기는 오류도 수정했습니다
https://github.com/user-attachments/assets/b57d8f80-e1b7-4521-b93e-a70cc9680d05

design: 전체 패딩값과 하단바 수정

---

src/common/User.tsx
src/components/EditProfile/WithdrawBtn.tsx
src/pages/Mypage.tsx
src/recoil/userAtoms.ts

마이페이지 초기 렌더링 시 Recoil의 user 상태 데이터를 먼저 사용하고, user.nickname 값이 없을 때에만 유저 상세 read API 요청을 실행하도록 했습니다.

feat: mypage 유저정보 연결

---

package-lock.json
src/api/boardApi.ts
src/pages/Board/type.tsx
yarn.lock

- 게시글 관련 API 요청을 처리하기 위해 `boardApi.ts` 파일 추가
- 게시글을 불러오고 표시하기 위해 `Board/type.tsx`에 API 연결 적용
- API 호출에 대한 에러 핸들링 추가 및 불러온 데이터 상태 관리 업데이트

feat: boardApi.ts 추가 및 Board/type.tsx 파일 API 연결 설정

---

src/components/BoardDetail/Footer.tsx
src/components/MapView/Header.tsx
src/components/MapView/MeetModal.tsx
src/pages/MapView.tsx

지도뷰에서 핀을 눌렀을때 밑에 나오게 되는 모임 모달창 ui 구현했습니다~

feat: 지도뷰 모임 모달창 ui 구현

---

package.json
src/common/Map.tsx
src/common/SideBar.tsx
src/components/BoardDetail/Comment.tsx
src/components/BoardDetail/CommentList.tsx
src/components/BoardDetail/Footer.tsx
src/components/BoardDetail/Update.tsx/Update.tsx
src/components/MapView/Content.tsx
src/components/MeetWrite/Calendar.tsx
src/components/MeetWrite/Content.tsx
src/components/MeetWrite/People.tsx
src/components/MeetWrite/Post.tsx
src/index.css
src/main.tsx
src/pages/BoardDetail.tsx
src/pages/MeetWrite.tsx
src/style.css
vite.config.ts
yarn.lock

다른 브라우저는 괜찮은데 휴대폰에서 사파리로 볼때 깨지는 현상 수정했습니다. 그리고 geolocation도 라이브러리 말고 window 내장되어있는 함수로 바꾸었고 스크롤 되는 페이지가 휴대폰에서 overscroll되어서 그것도 없어지도록 수정했습니다!

design: 사파리 화면 깨짐 수정 & geolocation 코드 변경 & overscroll없앰

---

src/App.tsx
src/components/Meet/MeetHeader.tsx
src/pages/Meet.tsx

1. feat: 모임 게시판 아이콘 변경 및 크기 조정
2. feat: 지도뷰 클릭시 /Map페이지로 이동.
3. feat: 모임목록, 게시판목록에서 각각 플러스 버튼 클릭시 새로운 게시물 생성 페이지로 이동

1. 모임게시판 아이콘 변경, 크기 조정. 2. 지도뷰 클릭시 이동. 3. 플러스 눌러 게시물 생성하기.

---

src/api/RemoveMeetRequest.ts
src/components/BoardDetail/CommentList.tsx
src/components/BoardDetail/Content.tsx
src/components/ChatDetail/Content.tsx
src/components/ChatDetail/Header.tsx
src/components/MapView/MeetModal.tsx
src/components/MeetDetail/Header.tsx
src/components/MeetDetail/RemoveMeet.tsx
src/components/MeetDetail/Update.tsx/Content.tsx
src/components/MeetDetail/Update.tsx/Footer.tsx
src/components/MeetDetail/Update.tsx/Header.tsx
src/components/MeetDetail/Update.tsx/Update.tsx
src/components/MeetWrite/Calendar.tsx
src/components/MeetWrite/People.css
src/pages/BoardDetail.tsx
src/pages/ChatDetail.tsx
src/pages/MeetDetail.tsx

모임 글쓰기에서 모바일에서 보면 달력이 잘리는 문제 해결했습니다. 그리고 채팅 헤더 부분 수정하고 모임 수정하는 ui 만들었습니다!
모임 수정하기 ui 는 글쓰기 ui랑 같아서 이미지 첨부는 생략했습니다~

모임 글쓰기 모바일에서 달력깨짐 문제 해결 & 채팅 헤더 수정  & 모임 수정하기 ui 

---

src/api/ReadBoardRequest.ts
src/api/ReadGatheringListRequest.ts
src/api/ReadMeetListRequest.ts
src/api/boardApi.ts
src/components/Meet/MeetHeader.tsx
src/pages/Board/type.tsx
src/pages/Meet.tsx

refactor : Meet, Board 관련 api 수정

---

src/api/BoardListRequest.ts
src/api/ReadMeetListRequest.ts

BoardListRequest.ts와 ReadMeetListRequest.ts에서
토큰 저장 방식 오류와 API Authorization 헤더 수정했습니다!!

refactor: API Authorization 헤더 수정

---

src/common/PlusImage.tsx
src/common/Slide.tsx
src/components/BoardDetail/Comment.tsx
src/components/BoardDetail/CommentList.tsx
src/components/BoardDetail/Footer.tsx
src/components/ChatDetail/Content.tsx
src/components/MeetDetail/Footer.tsx
src/pages/BoardDetail.tsx
src/pages/ChatDetail.tsx
src/pages/MeetDetail.tsx

fix: 수정사항 수정했습니다~

---

src/pages/Board/type.tsx

fix: 대소문자로 인한 게시판 라우팅문제 해결

---

src/common/PostList.tsx
src/components/UserInfo/UserTabs.tsx
src/pages/MyPageList.tsx
src/pages/MyPagePost/MyComments.tsx
src/pages/MyPagePost/MyPosts.tsx
src/pages/UserInfo.tsx

PostList에 lastPostRef를 추가해서 마지막 요소인지 감지하고 다음 페이지의 데이터를 불러올 수 있도록 했습니다

feat: 내가 작성한 게시물/댓글 api연결

---

src/components/BoardDetail/Comment.tsx
src/components/BoardDetail/CommentList.tsx
src/pages/BoardDetail.tsx

대댓글 달려고 할때 input창을 누르면 부모가 초기화되는 현상 해결했습니다!

fix: 대댓글 오류 해결

---

src/api/BoardListRequest.ts
src/pages/Board/type.tsx

게시물 리스트 명세서랑 맞게 데이터 매핑 수정했습니다
게시물 3개만 불러와지는 걸 무한스크롤로 바꿨습니다

fix: 게시물 리스트 api 수정

---

src/common/PostList.tsx
src/common/User.tsx
src/components/Board/Header.tsx
src/components/Search/Header.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchResult.tsx
src/index.css
src/pages/BlockedUserList.tsx
src/pages/Board.tsx
src/pages/Board/type.tsx
src/pages/Search.tsx
src/recoil/searchState.ts

전체에서 검색, 각각 게시판에서 검색 모두 구현했습니다
검색 후 input에 변화가 생기면 초기 화면으로 돌아가게 했습니다

feat: 게시물 검색

---

src/api/ReadMeetListRequest.ts
src/pages/Meet.tsx

사용자 프로필 이미지, 닉네임, 동네 표시
썸네일 중앙배치

fix:모임 목록속  컴포넌트 상세 썸네일

---

package-lock.json
src/api/HomePopularBoard.ts
src/pages/Home.tsx
yarn.lock

feat: home페이지 인기게시글 api연결

---

src/api/NotificationApi.ts
src/pages/Home.tsx
src/pages/Meet.tsx
src/pages/Notification.tsx

1. 홈에서 인기게시물 접근 라우팅 수정
2. 모임리스트에서 현재위치 받아오는 시점을 컴포넌트가 마운트되는 시점으로 변경
3. 모임리스트 디폴트값 변경
4. 알림기능을 위해 Notification.tsx, NotificationApi.ts 추가

홈에서 인기게시물 접근 수정, 모임리스트에서 현재위치 받아오는 시점 변경, 알림기능

---

src/components/BoardDetail/Comment.tsx
src/components/BoardDetail/Footer.tsx

fix: 수정에서 대댓글로 바꿀시 오류 수정

---

src/common/UserMore.tsx
src/components/BoardDetail/Footer.tsx

design: user모달창 간격 수정
